SK-1192 README and changelog update for token options in get interface
skyflowapi/skyflow-python pull request #113
Opened 2023-10-30 16:05 UTC by skyflow-lipsa

2023-10-31 05:05 UTC, skyflow-vivek requested changes

2023-10-31 05:05 UTC, skyflow-vivek commented on README.md
`Get` method is already mentioned in README. `Get with options` is not a new method.
Please use the existing `Get` section and update that only.
You can reference Java README.

2023-10-31 05:10 UTC, skyflow-lipsa commented on README.md
okay

2023-12-01 08:15 UTC, skyflow-vivek approved these changes

2023-12-01 08:16 UTC, skyflow-bharti approved these changes

2023-12-01 08:57 UTC, merged