[SDK-750] Update sample readme
skyflowapi/skyflow-python pull request #64
Opened 2022-10-18 08:38 UTC by skyflow-puneet

2022-10-18 08:46 UTC, Shaik-Luqmaan approved these changes

2022-10-19 18:09 UTC, manny-silva requested changes

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +# PYTHON-SDK sample templates
"# Python SDK samples"

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +Use this folder to test the functionalities of PYTHON-SDK just by adding `VAULT-ID` `VAULT-URL` and `SERVICE-ACCOUNT` details at the required place.
"Test the SDK by adding `VAULT-ID`, `VAULT-URL`, and `SERVICE-ACCOUNT` details in the required places for each sample."

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- A Skylow account. If you don't have one, you can register for one on the [Try Skyflow](https://skyflow.com/try-skyflow) page.
"- A Skyflow account. If you don't have one, register for one on the [Try Skyflow](https://skyflow.com/try-skyflow) page."

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- Before you can run the sample app, create a vault
Delete. The next section is about creating a vault.

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- The package can be installed using pip:
"Install the Python SDK:

```python
pip install skyflow
```
"

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +## Configure
"## Prepare"

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +1. In a browser, navigate to Skyflow Studio and log in.
"1. In a browser, sign in to Skyflow Studio."

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +3. Once the vault is created, click the gear icon and select **Edit Vault** Details.
"3. Once the vault is ready, click the gear icon and select **Edit Vault Details**."

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +4. Note your Vault URL and Vault ID values, then click Cancel. You'll need these later.
"4. Note your **Vault URL** and **Vault ID** values, then click **Cancel**. You'll need these later."

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +2. For Name, enter **Test-Python-Sdk-Sample**. For Roles, choose the required roles for specific action.
"2. For **Name**, enter "SDK Samples". For **Roles**, choose **Vault Editor**.

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +3. Click **Create**. Your browser downloads a **credentials.json** file. Keep this file secure, as you'll need it in the next steps.
"3. Click **Create**. Your browser downloads a **credentials.json** file. Keep this file secure. You'll need it for each of the samples."

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +### Different types of functionalities of Java-Sdk
"## The samples"

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- [**Detokenize**](detokenize_sample.py)
"### [**Detokenize**](detokenize_sample.py)"

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +    - Make sure the token is of the data which exists in the Vault. If not so please make use of [insert_sample.py](insert_sample.py) to insert the data in the data and use this token for detokenizat
"Detokenize a data token from the vault. Make sure the specified token is for data that exists in the vault. If you need a valid token, use [insert_sample.py](insert_sample.py) to insert the data, then use this data's token for detokenization."

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +    - Configure
"#### Configure"

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +        - Replace **<YOUR_CREDENTIALS_FILE_PATH>** with relative  path of **SERVICE ACCOUNT CREDENTIAL FILE**.
Change this whole list to an ordered list.

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +    - Execution
"#### Run the sample"

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +            python3 detokenize_smaple.py
```bash
python3 detokenize_smaple.py
```

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- [**GetById**](get_by_ids_sample.py)
Same formatting comments as previous sample.

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- [**Insert**](insert_sample.py)
Same formatting comments as previous sample

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- [**InvokeConnection**](invoke_connection_sample.py)
Same formatting comments as previous sample

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- [**Service account token generation**](sa_token_Sample.py)
Same formatting comments as previous sample

2022-10-19 18:09 UTC, manny-silva commented on samples/README.md
> +- [**Generate Bearer Token From Credentails**](generate_bearer_token_from_creds_sample.py)
Same formatting comments as previous sample

2022-10-19 18:18 UTC, manny-silva requested changes

2022-10-19 18:18 UTC, manny-silva commented on samples/README.md
> +- Python 3.7.0 and above.
- Python 3.7.0 or higher.

2022-10-27 17:50 UTC, manny-silva commented
Reformatted the sample readme with the following content. Would've committed directly myself, but I don't have edit access to this repo yet.

# Python SDK samples

Test the SDK by adding `VAULT-ID`, `VAULT-URL`, and `SERVICE-ACCOUNT` details in
the required places for each sample.

## Prerequisites

- A Skyflow account. If you don't have one, register for one on the
  [Try Skyflow](https://skyflow.com/try-skyflow) page.
- Python 3.7.0 or higher.

## Prepare

### Install the Python SDK

```bash
pip install skyflow
```

### Create the vault

1. In a browser, sign in to Skyflow Studio.
2. Create a vault by clicking **Create Vault** > **Start With a Template** >
   **Quickstart vault**.
3. Once the vault is ready, click the gear icon and select **Edit Vault Details**.
4. Note your **Vault URL** and **Vault ID** values, then click **Cancel**.
   You'll need these later.

### Create a service account

1. In the side navigation click, **IAM** > **Service Accounts** > **New Service Account**.
2. For **Name**, enter "SDK Sample". For **Roles**, choose **Vault Editor**.
3. Click **Create**. Your browser downloads a **credentials.json** file. Keep
   this file secure, as You'll need it for each of the samples.

## The samples

### [Get data by ID](./getByIDSample.py)

Get data using Skyflow IDs for the desired records.

#### Configure

Replace the following values in the sample file:

| Value                          | Description                                             |
| ------------------------------ | ------------------------------------------------------- |
| `<YOUR_VAULT_ID>`              | ID of your vault.                                       |
| `<YOUR_VAULT_URL>`             | URL of your vault.                                      |
| `<SKYFLOW_ID1>`                | Skyflow ID of the first record.                         |
| `<SKYFLOW_ID2>`                | Skyflow ID of the second record.                        |
| `<SKYFLOW_ID3>`                | Skyflow ID of the third record.                         |
| `<YOUR_CREDENTIALS_FILE_PATH>` | relative path to your service account credentials file. |
| `<TABLE_NAME>`                 | Name of the table to get data from.                     |

#### Run the sample

```bash
python3 getByIDSample.py
```

### [Insert data](./InsertSample.py)

Insert data in the vault.

#### Configure

Replace the following values in the sample file:

| Value                          | Description                                             |
| ------------------------------ | ------------------------------------------------------- |
| `<YOUR_VAULT_ID>`              | ID of your vault.                                       |
| `<YOUR_VAULT_URL>`             | URL of your vault.                                      |
| `<YOUR_CREDENTIALS_FILE_PATH>` | relative path to your service account credentials file. |
| `<TABLE_NAME>`                 | Name of the table to insert data into.                  |
| `<FIELD_NAME>`                 | Name of the column to insert data into.                 |
| `<VALUE>`                      | Valid value to insert into the corresponding column.    |

#### Run the sample

```bash
python3 InsertSample.py
```

### [Detokenize data](./detokenizeSample.py)

Detokenize a data token from the vault. Make sure the specified token is for
data that exists in the vault. If you need a valid token, use
[insert_sample.py](insert_sample.py) to insert the data, then use this data's
token for detokenization.

#### Configure

Replace the following values in the sample file:

| Value                          | Description                                             |
| ------------------------------ | ------------------------------------------------------- |
| `<YOUR_VAULT_ID>`              | ID of your vault.                                       |
| `<YOUR_VAULT_URL>`             | URL of your vault.                                      |
| `<YOUR_CREDENTIALS_FILE_PATH>` | relative path to your service account credentials file. |
| `<FIELD_NAME>`                 | Name of the column to insert data into.                 |
| `<TOKEN>`                      | Token for the data you want to detokenize.              |

#### Run the sample

```bash
python3 detokenizeSample.py
```

### [Invoke a connection](./invokeConnectionSample.py)

Skyflow Connections is a gateway service that uses Skyflow's underlying
tokenization capabilities to securely connect to first-party and third-party
services. This way, your infrastructure is never directly exposed to sensitive
data, and you offload security and compliance requirements to Skyflow.

#### Configure

Replace the following values in the sample file:

| Value                          | Description                                             |
| ------------------------------ | ------------------------------------------------------- |
| `<YOUR_VAULT_ID>`              | ID of your vault.                                       |
| `<YOUR_VAULT_URL>`             | URL of your vault.                                      |
| `<YOUR_CREDENTIALS_FILE_PATH>` | relative path to your service account credentials file. |
| `<YOUR_CONNECTION_URL>`        | URL of your connection.                                 |
| `<YOUR_CONNECTION_BASIC_AUTH>` | Access token for your connection.                       |
| `requestBody`                  | Your request body content.                              |
| `pathParams`                   | Your path parameters.                                   |

#### Run the sample

```bash
python3 invokeConnectionSample.py
```

### [Service account token generation](./SATokenSample.py)

Generates SA Token using path of credentials file.

#### Configure

Replace `<YOUR_CREDENTIALS_FILE_PATH>` with the relative path to your service account credentials file.

#### Run the sample

```bash
python3 SATokenSample.py
```

### [Generate Bearer Token](./generateBearerTokenFromCredsSample.py)

Generates SA Token using json content of credentials file.

#### Configure

Replace `credentials` with the content of service account credentials file.

#### Run the sample

```bash
python3 generateBearerTokenFromCredsSample.py
```

2022-10-27 20:54 UTC, manny-silva approved these changes

2022-11-02 12:07 UTC, merged